### ISSUE TITLE
Parse priority value for MX, SRV and URI

### ISSUE THREAD

**Issue by NGPixel** [silverwind/dnsz#5]
It would be great if the priority value could be parsed when the record is of type MX, SRV or URI.

For example:
```
gsuite.example.com.	1	IN	MX	10 alt4.aspmx.l.google.com.
```
would return:
```js
{
  name: 'gsuite.example.com',
  ttl: 1,
  class: 'IN',
  type: 'MX',
  priority: 10,
  content: 'alt4.aspmx.l.google.com.',
  comment: null
}
```

**Comment by silverwind** [comment]
Sorry, but I have to reject, parsing of `content` is explicitely out of scope for this module, so that it can stay compatible with any future new record types without change.
